<?php

namespace App\Repositories;

use App\Models\Question;

class QuestionRepository extends BaseRepository
{
    public function __construct()
    {
        parent::__construct();
        $this->list_search_fields = ['name', 'code'];
        $this->tenant_id = TENANT_ID_DEFAULT;
    }

    public function getModel()
    {
        return Question::class;
    }

    public function genCodeQuestion()
    {
        $tenant_id = $this->tenant_id;
        do {
            $code = rand(100000, 99999999);
            $info = Question::where('code', $code)->where('tenant_id', $tenant_id)->first();
        } while (!is_null($info));

        return $code;
    }

    public function create($data)
    {
        $data['content'] = createFileFromContentBase64($data['content']);
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
